### ISSUE TITLE
triobin documentation

### ISSUE THREAD

**Issue by nhartwic** [lh3/yak#17]
I'm currently trying to bin HiC reads in order to attempt to do haplotype specific scaffolding of a phased hifiasm assembly. I was hoping I could use yaks triobinning functionality to get hapmer counts associated with each read, so that I could then attempt to bin the read pairs.

The issue I'm running into is that triobin has no meaningful documentation at the moment. It produces an output table with 10 columns. The first is a contig id. The second is yaks binning result which is useless to me. I'm hoping that the actual counts are somewhere in the remaining 8 columns.

So what are the columns in triobin output?

**Comment by lh3** [comment]
For your purpose, you may try `trioeval`. On S-lines, the first two numbers give the father- and mother-specific counts.

**Comment by nhartwic** [comment]
I was rather hoping to get counts for: parent1_specific, parent2_specific, both, neither.

Any chance you could explain the output of triobin anyway? I assume the table isn't just gibberish. What are the numbers supposed to mean?

**Comment by Dmitry-Antipov** [comment]
Hi,
I'm not a yak's developer, but since I've looked on the source code for a while with exactly the same question will try to answer

So, as far as I see the format is <sequence name> <decision> <paternal kmer count0> <maternal kmer count0> <paternal kmer count1> <maternal kmer count1>  ? ? <sequence length in kmers> ?

count1 is just total count of maternal/paternal kmers, count0 is a count of kmers in stripes (of length k-4 or larger) of maternal/paternal haplotypes. Counts of kmers in stripes of consecutive haplotype specific kmers are more reliable than just kmer counts, because even one nucleotide difference between haplotypes gives you not one haplotype specific k-mer but about k (can be less than k  in repetitive regions)

Did not get the meaning of fields 7,8,10 - they are not used for classification.

Once again - I'm not a yak's developer so it's possible that I've got something wrong.
